---
- name: Installer Zabbix Server (avec PostgreSQL)
  hosts: localhost
  become: true

  tasks:
    - name: Ajouter dépôt Zabbix
      apt_repository:
        repo: "deb http://repo.zabbix.com/zabbix/6.0/ubuntu {{ ansible_distribution_release }} main"
        state: present
        filename: zabbix

    - name: Importer la clé GPG Zabbix
      apt_key:
        url: https://repo.zabbix.com/zabbix-official-repo.key
        state: present

    - name: Mettre à jour les paquets
      apt:
        update_cache: yes

    - name: Installer Zabbix Server, Frontend, Agent, PostgreSQL
      apt:
        name:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
          - postgresql
          - postgresql-contrib
        state: present
